server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/raspberry?useUnicode=true&characterEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
mybatis:
  type-aliases-package: com.fiany.utilproject.bean
